### ISSUE TITLE
Query regarding OpenOmci extension

### ISSUE THREAD

**Issue by mphaneendra** [cboling/omci#2]
Hi Chip Boling,

I would like to know is this project a go version of OpenOmci extension in VOLTHA(https://github.com/opencord/voltha/tree/master/voltha/extensions/omci)

If yes, what are the feature differences between OpenOmci extension in VOLTHA and this project ?
And when this project would be ready to integrate in VOLTHA Go version ?

Thanks in Advance :)

Thanks,
Phaneendra

**Comment by cboling** [comment]
This is the python version of OpenOMCI that is part of VOLTHA




There currently not any plans for a Go version.




    Chip




On Mon, Jan 21, 2019 at 8:44 AM -0600, "mphaneendra" <notifications@github.com> wrote:












Hi Chip Boling,


I would like to know is this project a go version of OpenOmci extension in VOLTHA(https://github.com/opencord/voltha/tree/master/voltha/extensions/omci)


If yes, what are the feature differences between OpenOmci extension in VOLTHA and this project ?

And when this project would be ready to integrate in VOLTHA Go version ?


Thanks in Advance :)


Thanks,

Phaneendra

**Comment by cboling** [comment]
Hi Phaneendra,

Just got a chance to really look at the email you sent and I did not notice at first that it was for this repository  (read it on my smartphone before my morning coffee :-)

This library is my initial work on serialization/decode of OMCI packets that could be used in the future for a Go version of OpenOMCI, but its first use is for my ONU Mock go program where I am planning on simulating many ONUs so we can both stress test OpenOMCI via BBSIM.   From this I hope to see if there is even a need for a go-based ONU device adapter since OpenOMCI has quite a few state machines.  Since we will be containerized soon, there are so many different ways to improve performance and scalability without rewriting entire adapters.

One other difference to note is that the ONU Mock will use the gopacket library as an ONU does and OpenOMCI would use it as an OLT does.  I am trying to write many of the MEFrame.py related methods in go, but once again, with an initial ONU focus.   (I am actually doing that work right now).

My goal is to get the OMCI and ONU-Mock ready for demo by the end of March.
